### ISSUE TITLE
Delete policy rule from list view error

### ISSUE THREAD

**Issue by collin-wicker** [nautobot/nautobot-app-firewall-models#251]
### Environment
* Python version:  3.9.18
* Nautobot version:  2.2.0b1
* nautobot-firewall-models version:  2.0.3

### Expected Behavior
From Policy Rule list view expected to be able to select a policy rule and "Delete Selected" button.

### Observed Behavior
Received the below error:

<class 'AttributeError'>

'PolicyRuleUIViewSet' object has no attribute 'obj'

### Steps to Reproduce
1. Navigate to Policy Rules list view and select a single policy rule
2. Click the "Delete Selected" button to delete the selected rule

**Comment by gsnider2195** [comment]
This is working correctly in Nautobot v2.3.1. @collin-wicker can you confirm?

**Comment by robertoduarte-codilime** [comment]
I just confirmed  the issue is no longer reproducible, even in the initially referenced version.
